# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-01 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_calendar_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='RedemptionPage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class.RedemptionPage'),
            preserve_default=False,
        ),
    ]
