# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_remove_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
